version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 2402:443
    volumes:
      - ./demo/default.conf:/etc/nginx/conf.d/default.conf
      - ./demo/localhost.crt:/certificate.crt
      - ./demo/localhost.key:/private.key
    depends_on:
      - webserver
  postgresql:
    image: postgres:15
    volumes:
      - ./demo/docker/pg-data:/var/lib/postgresql/data
      - ./demo/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: nostr
      POSTGRES_DB: saltivka_development
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis/redis-stack-server
    environment:
      - REDIS_ARGS=--maxmemory 2GB --maxmemory-policy noeviction --maxclients 10000 --tcp-backlog 511 # https://github.com/redis-stack/redis-stack/issues/110
  db-migration:
    image: saltivka
    env_file: ./demo/.env
    command: sh -c "until bundle exec rails db:migrate db:seed; do sleep 5; done"
    depends_on:
      - postgresql
      - redis
  webserver:
    image: saltivka
    env_file: ./demo/.env
    ports:
      - 3000:3000
    depends_on:
      - postgresql
      - redis
      - db-migration
  worker:
    image: saltivka
    env_file: ./demo/.env
    command: bundle exec sidekiq -q nostr
    depends_on:
      - postgresql
      - redis
      - db-migration
