version: "3"
services:
  sidekiq_redis:
    image: redis:7
    ports:
      - 63790:6379
    volumes:
      - ./docker/sidekiq-redis-data:/data
  sidekiq_redis_test:
    image: redis:7
    ports:
      - 63791:6379
    volumes:
      - ./docker/sidekiq-redis-test-data:/data
  redis:
    image: redis/redis-stack-server:7.2.0-v0
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis-data:/data
  redis_test:
    image: redis/redis-stack-server:7.2.0-v0
    ports:
      - 63792:6379
    volumes:
      - ./docker/redis-test-data:/data
  postgresql:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: saltivka_development
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ./docker/pg-data:/var/lib/postgresql/data